# Generated by Django 4.1.7 on 2023-05-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='consultor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
