# Generated by Django 4.1.7 on 2023-05-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_alter_curso_consultor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aprenderas',
            field=models.TextField(null=True),
        ),
    ]
